### ISSUE TITLE
Set default value for instance_tenancy

### ISSUE THREAD

**Issue by comeanother** [cloudposse/terraform-aws-vpc#11]
## conditions

* Use s3 backend for `.tfstate` file
* Do `terraform apply` on the one host
* Do `terraform plan` on another host
* VPC is going to be recreated because `instance_tenancy` is going to be changed

![image](https://user-images.githubusercontent.com/11299538/33437965-332f1a18-d5f2-11e7-97b0-d27e9c7795d0.png)

**Comment by comeanother** [comment]
Possible solution.
Set `default` as a default value for `instance_tenancy` in the module.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-vpc/releases/tag/0.3.1
