### ISSUE TITLE
Remove classiclink support

### ISSUE THREAD

**Issue by cdobbyn** [cloudposse/terraform-aws-vpc#111]
## Describe the Bug
New versions of the AWS provider are now warning about the deprecated setting `enable_classiclink` as this functionality no longer exists within AWS.

## Expected Behavior
No warning appears.

## Steps to Reproduce
1. Update your AWS provider to the latest version
2. Try to run a terraform plan for a new or existing VPC.

## Screenshots
n/a - see additional context

## Environment (please complete the following information):
terraform 1.2.x
aws provider 4.29.0

## Additional Context
Fixing this issue will reduce backwards compatibility with older aws providers which required this setting.

Example output:
```
╷
│ Warning: Argument is deprecated
│ 
│   with module.access_vpc_01.module.this_vpc.aws_vpc.default,
│   on .terraform/modules/access_vpc_01.this_vpc/main.tf line 40, in resource "aws_vpc" "default":
│   40:   enable_classiclink               = local.classiclink_enabled
│ 
│ With the retirement of EC2-Classic the enable_classiclink attribute has
│ been deprecated and will be removed in a future version.
│ 
│ (and 7 more similar warnings elsewhere)
╵

```

**Comment by babebort** [comment]
thill the same


` Warning: Argument is deprecated
│ 
│   with module.vpc.aws_vpc.default[0],
│   on .terraform/modules/vpc/main.tf line 40, in resource "aws_vpc" "default":
│   40:   enable_classiclink               = local.classiclink_enabled
│ 
│ With the retirement of EC2-Classic the enable_classiclink attribute has been deprecated and will be removed in a future version.
│ 
│ (and one more similar warning elsewhere)
`
