### ISSUE TITLE
Implement CI/CD with Codefresh

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-aws-vpc#18]
### preparation
1. Create `examples/` folder with working examples. one per subdirectory.
2. Use this as a test case
```
module "vpc" {
  source    = "...relateive path..."
  namespace = "eg"
  stage     = "testing"
  name      = "app"
}
```

### CI/CD
1. use codefresh to run a temporary container with tf module code
e.g.
```
docker run -v examples/:/conf/ testing.cloudposse.co
```

Then for each project in `examples/`, do the following:
2. run `init-terraform` to set remote state
3. run `terraform plan`
4. use `github-commenter` to paste output to github PR
5. run `terraform apply` if previous steps succeeded
6. use `github-commenter` to paste output to github PR
7. run `terraform destroy` if previous steps succeeded
8. run `github-commenter` to paste output to github PR

## why
* Ensure module is functioning

**Comment by aknysh** [comment]
should we start adding `Dockerfile` to each of our TF modules?
it will inherit from the `geodesic` image.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-vpc/releases/tag/0.5.0
