### ISSUE TITLE
cidr_block required for vpc module

### ISSUE THREAD

**Issue by rtomlinson-latacora** [cloudposse/terraform-aws-vpc#30]
Hello,

I'm looking for some clarification in the documentation regarding the cidr_block input for the vpc module. The documentation says it's required but the examples don't include the input. I tried to deploy a vpc using the dynamic_subnets module and got an error stating the cidr_block was required for the vpc module. Maybe there's more going on than is evident from the documents? I was able to deploy a vpc by including the cidr_block input on the vpc module. Thanks for your time.

**Comment by aknysh** [comment]
@rtomlinson-latacora thanks for testing the module.
`cidr_block` was optional (had a default value), but was removed in this PR https://github.com/cloudposse/terraform-aws-vpc/pull/24

Unfortunately the examples in `README` were not updated

**Comment by rtomlinson-latacora** [comment]
Hey @aknysh,

Thanks for the response and clarification.
I can put in a PR to update the docs unless you have someone else that does periodic updates.

Best,
Renzo

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-vpc/releases/tag/0.5.0
