### ISSUE TITLE
Default VPC option?

### ISSUE THREAD

**Issue by hongkongkiwi** [cloudposse/terraform-aws-vpc#66]
Is there a way to set this VPC as the default VPC? I couldn't seem to find it in the module.

**Comment by nitrocode** [comment]
From the [`aws_vpc`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc) resource docs, there isn't an option to set a VPC as a default VPC.

It does look possible to create a default VPC from the [AWS console and awscli](https://serverfault.com/a/915968/320458).

I believe you may be looking for the [`aws_default_vpc`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_vpc) resource.

> For AWS accounts created after 2013-12-04, each region comes with a Default VPC. This is an advanced resource, and has special caveats to be aware of when using it. Please read this document in its entirety before using this resource.
> The aws_default_vpc behaves differently from normal resources, in that Terraform does not create this resource, but instead "adopts" it into management.

If we did add this separate resource, it would have to be created on a toggle meaning that you could not set an existing VPC as a default.

**Comment by Nuru** [comment]
No, this module does not create a default VPC. Managing the default VPC for an account is a different kind of task than managing one or more non-default VPCs and so we are not going to add that feature to this module because it is not a good fit.
