### ISSUE TITLE
Single Nat Gateway

### ISSUE THREAD

**Issue by Guy-Rawsthorn** [cloudposse/terraform-aws-vpc#87]
Is there any way to restrict the number of Nat Gateways created?
would be useful for a single_nat_gateway input?

**Comment by nitrocode** [comment]
This module does not manage the [`aws_nat_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway) resource. You may be looking for the [cloudposse/terraform-aws-named-subnets](https://github.com/cloudposse/terraform-aws-named-subnets) or the [cloudposse/terraform-aws-dynamic-subnets](https://github.com/cloudposse/terraform-aws-dynamic-subnets) modules.
