### ISSUE TITLE
Version constrained to old v2 AWS module

### ISSUE THREAD

**Issue by antgel** [cloudposse/terraform-aws-vpc#90]
The last released v2 was 2.70.0 in June 2020. It would be great to be able to use this module with 3.x.x (up to 3.47.0 at the time of writing).

**Comment by paulcrussell** [comment]
+1

**Comment by Nuru** [comment]
This module has not been constrained to AWS v2 since #64 and `terraform-aws-vpc` release 0.16.2 almost a year ago.
