### ISSUE TITLE
Default security group behavior change

### ISSUE THREAD

**Issue by jrmcpeek** [cloudposse/terraform-aws-vpc#91]
## Describe the Bug
Feature commit f875913e1732cd9f1d27ac4277403da851eaa17f looked to use the terraform-aws-security-group module rather than the base `resource`.

However, this change makes a new group and just calls it the default group, but doesn't actually manage / reference the `default` security group in the VPC, as was done previously.

## Expected Behavior
VPC creation has hooks for managing the default security group, not creating a non-default security group and calling it default.

## Steps to Reproduce
1. Follow the complete example in this repository
2. Behold you end up with two security groups, with the one flagged not named default is labeled "Default Security Group"

## Additional Context
This is a regression on previous behavior.

Appears unintentional.

**Comment by nitrocode** [comment]
Use the latest non prerelease version v0.25.0 to avoid this problem. The latest version is still waiting on a new refactor of the security group module.
